### ISSUE TITLE
Making images sit on baseline

### ISSUE THREAD

**Issue by shreevatsa** [pkra/mathjax-node-svg2png#12]
Thanks for this tool. I tried this today (via Pandoc), and ran into a couple of inconveniences.

The first one was that the default rendering was too blurry, but I was able to work around that by setting the `scale` option in the input to 4, and dividing the `pngWidth` in the output by 4 to set as the image width. (Thanks!)

The remaining problem it seems is that baseline information is lost, so the entire image sits above the baseline of text awkwardly; see image below:

![image](https://user-images.githubusercontent.com/767530/64646489-10ca6700-d3cc-11e9-9ac6-2df7892a9e9b.png)

Compare that to SVG rendering, which does not have the problem:

![image](https://user-images.githubusercontent.com/767530/64646807-a0701580-d3cc-11e9-9d57-cc5ea3b16e60.png)

I don't know the internals of svg2png, but would it be possible to provide some information in the output that can be used to position the image properly?

**Comment by pkra** [comment]
First off, you probably shouldn't use this tool since it hasn't been updated in 2 years. (And I should probably mark it as unmaintained).

With a recent version of mathjax-node, the returned object will include width, height and style keys, cf. https://github.com/mathjax/MathJax-node#promiseresolveresultoptions--promiserejecterrors--callbackresult-options. 

This is to some degree accidental (as this library internally switches the SVG output on but then later removes the SVG output for slimmer results - but it's so sold it leaves the new keys tied to SVG output in the result). But see the first paragraph.

**Comment by pkra** [comment]
> With a recent version of mathjax-node, the returned object will include width, height and style keys,

To clarify: the styles include vertical-align values to correct the baseline.

**Comment by shreevatsa** [comment]
Thanks for the quick reply! Including the `vertical-align` returned from `mjAPI.typeset` seems to fully solve the issue. 

At first it seemed to be a tiny bit off:

![image](https://user-images.githubusercontent.com/767530/64701209-2d62af80-d45d-11e9-8277-da35d9aa8217.png)

but after measuring the "ex" from the font (was about 7.17 instead of the default 6, for Times on my browser) and passing that in to `mjAPI.typeset`, the results look great:

![image](https://user-images.githubusercontent.com/767530/64702226-fd1c1080-d45e-11e9-811d-0ebd0763da23.png)

----

On not using this tool: Is there an alternative way of getting png output from MathJax, that you would recommend? In the [README for MathJax-node](https://github.com/mathjax/MathJax-node/blob/7d74722/README.md#breaking-changes-in-v10), it's written that PNG generation was removed in v1.0 but can “easily be recreated” and points to this one... if this tool went away I'd probably try to find a version of MathJax pre-v1.0 and that would be even older :-) (I guess one alternative would be bypassing MathJax and using LaTeX + dvipng or something like that.)

**Comment by pkra** [comment]
Glad it worked. Note that MathJax creates various style declarations, in particular margins, including negative ones.

As for using this tool, I think a post-processor is a more reasonable approach (instead of a drop-in replacement). But more importantly, this repo use svg2png whose last release is 3 years old and which is based on phantomjs which is dead.

These days, I usually just pipe the svg output to puppeteer, e.g., here's a super simple starting point https://github.com/pkra/ebookcraft2018/blob/20759ad39ab2e69d056a7dba7aae453cab9048d1/06-sample/main-png.js#L8-L16. Or you can pick one of the many  SVG-to-PNG tools https://www.npmjs.com/search?q=svg%20to%20png to make your life easier.

**Comment by shreevatsa** [comment]
Thanks for the references! I'll try them out next time. If I understand correctly, the suggestion of using a post-processor is to recognize SVG images inserted by MathJax and convert each of them to PNG... that sounds reasonable indeed.

Via the link you gave, I found your https://pkra.github.io/ebookcraft2018/ which is very informative. To add some background for why I was trying to do all this: it was to send a single email to Gmail recipients that contains some mathematics... I found that Gmail does not support SVG so for mathematics one needs to either (1) attach as a PDF, (2) write something like LaTeX markup directly in the body (and hope that the reader can either mentally parse it or has something special installed that does so), (3) use embedded (attached or externally linked) PNG images, which Gmail fortunately does seem to support. 

In the process of doing the last I was trying to get a web page first (to copy into Gmail), and ran into this baseline problem (now solved with your help) for displaying the web page. But ultimately for the email I ended up avoiding images for all inline mathematics and using the minimal number of images. Pandoc has a mode where it tries to convert simple math expressions into simple (ugly but) readable html (using `<em>` and `<sup>` tags, and Unicode for things like ∑), so I used that as much as possible and only used images when really necessary.

Maybe someday I can look further into this strange task of converting a document containing mathematics into a Gmail-supported subset of HTML+[CSS](https://developers.google.com/gmail/design/reference/supported_css)+images (please let me know if you have suggestions for a mailing list or some place to post what I tried/found, and further questions); feel free to close this bug now and thanks for your help!

**Comment by pkra** [comment]
Oh, emails! Yes, a world of pain. I think img tags with SVG can be an option nowadays (support is good enough but varies with user base, especially regionally). I'd have suggetsed font-independent HTML+CSS as well; the quality is not TeX-level but very reasonable (e.g., MathJax old PreviewHTML output).
